/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deFiOneSol from "./DeFiONE.sol";
export type { deFiOneSol };
export type { MyContract } from "./MyContract";
export type { Staking } from "./Staking";
