/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as deFiOneSol from "./DeFiONE.sol";
export { MyContract__factory } from "./MyContract__factory";
export { Staking__factory } from "./Staking__factory";
