/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zetachain from "./@zetachain";
export type { zetachain };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { IZRC20 } from "./@zetachain/protocol-contracts/contracts/zevm/interfaces/IZRC20";
export { IZRC20__factory } from "./factories/@zetachain/protocol-contracts/contracts/zevm/interfaces/IZRC20__factory";
export type { ZContract } from "./@zetachain/protocol-contracts/contracts/zevm/interfaces/ZContract";
export { ZContract__factory } from "./factories/@zetachain/protocol-contracts/contracts/zevm/interfaces/ZContract__factory";
export type { SystemContract } from "./@zetachain/protocol-contracts/contracts/zevm/SystemContract.sol/SystemContract";
export { SystemContract__factory } from "./factories/@zetachain/protocol-contracts/contracts/zevm/SystemContract.sol/SystemContract__factory";
export type { SystemContractErrors } from "./@zetachain/protocol-contracts/contracts/zevm/SystemContract.sol/SystemContractErrors";
export { SystemContractErrors__factory } from "./factories/@zetachain/protocol-contracts/contracts/zevm/SystemContract.sol/SystemContractErrors__factory";
export type { MyContract } from "./contracts/MyContract";
export { MyContract__factory } from "./factories/contracts/MyContract__factory";
